### PR TITLE
rewrite/fixes the structure/commands of pirateship

### LINKED ISSUE #33: pirateship restructure and pending commands

### PR DESCRIPTION
**Pull request by i5o**
fixes #33

### CODE REVIEW

File: cli.js [hunk 1]
```diff
@@ -1,109 +1,93 @@
...
-  .action(password)
-
-var sshkeyadd = require('./lib/sshkeyadd.js')
-
-program
-  .command('sshkeyadd <public_key>')
-  .description('add a public key to `pi` and `root` user\'s authorized_keys')
-  .action(sshkeyadd)
-
+program.allowUnknownOption(false)
```
Comment (i5o) [inline cli.js]: this was a test, we could just keep it the old way

**Review by dogi — APPROVED** [review]
